/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package gh.merge.queue.test.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun testGetMessage() {
        assertEquals("Hello          World!!!", MessageUtils.getMessage1())

        assertEquals("Hello          World!!!", MessageUtils.getMessage2())

        assertEquals("3 Hello          World!!!", MessageUtils.getMessage3())
    }
}
