/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package gh.merge.queue.test.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest2 {
    @Test fun testGetMessage() {
        assertEquals("Hello          World!!!", MessageUtils.getMessage())
    }

}
