/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gh.merge.queue.test.app

import gh.merge.queue.test.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage1())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
