/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gh.merge.queue.test.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello          World!"
    }
}
